name: Backend Build Test

on:
  # pull_request:
  #   branches: [ develop ]
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write

    defaults:
      run:
        shell: bash
        working-directory: ./backend

    steps:
    - name: access to secret Test
      run: echo "$MY_SECRET"
      env:
        MY_SECRET: ${{secrets.NAME_TEST}}
    
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: ./gradlew build
