name: secret-test

on:
  workflow_dispatch

jobs:
  echoing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - name: access to secret Test
      run: echo "$MY_SECRET"
      env:
        MY_SECRET: ${{secrets.NAME_TEST}}
